version: '3.8'

services:
  # Serviço do MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
    restart: always

volumes:
  mongodb_data:
  neo4j_data:
